# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 12:09
from __future__ import unicode_literals

import apps.events.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('style', models.CharField(max_length=255, verbose_name='Стиль')),
                ('img', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.events.models.artists_upload_location, verbose_name='Фото')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Созданно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировано')),
                ('poster', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.events.models.upload_location, verbose_name='Афиша')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventArtistRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='artists', through='events.EventArtistRel', to='events.Artist', verbose_name='Артисты'),
        ),
    ]
