# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 13:35
from __future__ import unicode_literals

import apps.events.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('img', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=apps.events.models.showman_upload_location, verbose_name='Фото')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Ведущие',
                'verbose_name': 'Ведущий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='showmen',
            field=models.ManyToManyField(related_name='showmen', to='events.Showman', verbose_name='Ведущие'),
        ),
    ]
