# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170923_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artists', through='events.EventArtistRel', to='events.Artist', verbose_name='Артисты'),
        ),
    ]
