# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_lunch',
            field=models.BooleanField(default=False, verbose_name='Ланч'),
        ),
    ]
