# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_is_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_fire',
            field=models.BooleanField(default=False, verbose_name='На огне'),
        ),
    ]
