# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_is_fire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Код'),
        ),
    ]
