# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='count',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Количество (250/0.75)'),
        ),
    ]
