# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 12:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Код')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото')),
                ('likes', models.IntegerField(blank=True, null=True, verbose_name='Likes')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Созданно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активированно')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='instagram.Category', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagram',
            },
        ),
    ]
