# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 12:09
from __future__ import unicode_literals

import apps.gallery.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Созданно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировано')),
                ('main_image', models.ImageField(upload_to=apps.gallery.models.album_upload_location, verbose_name='Обложка')),
                ('cropping', image_cropping.fields.ImageRatioField('main_image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='events.Event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Созданно')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to=apps.gallery.models.upload_location, verbose_name='Фото')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.Album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
