# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-event__date'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
    ]
