# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-11 12:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20171002_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='event',
        ),
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 11, 12, 8, 35, 161365), verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='event', max_length=256, verbose_name='Событие'),
            preserve_default=False,
        ),
    ]
